version: '3.8'
services:
  pokedex-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api-service-mongo
    networks:
      - pokedex-bridge-network

  api-service-mongo:
    container_name: api-service-mongo
    image: mongo:6.0
    env_file:
      - .env
    restart: always
    ports:
      - '27017:27017'
    networks:
      - pokedex-bridge-network

networks:
  pokedex-bridge-network: